using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WomenSafety.Domain.Entities;
using WomenSafety.Domain.Enums;

namespace WomenSafety.Api.Data;

/// <summary>
/// Seeds the aggregated district safety directory — every police station (thana) of all
/// 64 districts, district/upazila hospitals, women's centres (AWCF, OSCC), help centres
/// (District Legal Aid Offices), fire stations and DC offices — from
/// <c>Data/directory-entries.json</c>.
///
/// The JSON is generated by <c>data-sources/build_directory_data.py</c> from open sources
/// (CC0 thana directory, judiciary.gov.bd contacts, published hospital contact lists).
///
/// Idempotent: a <see cref="DataSource"/> marker row guards the seed so an existing
/// database upgrades in place the first time this code runs; legacy demo placeholders
/// are removed in the same pass.
/// </summary>
public static class DirectorySeedData
{
    public const string SourceName = "District safety directory (aggregated open sources)";

    /// <summary>Guards against re-seeding when the dataset has not changed.</summary>
    private const string VersionPrefix = "v2-";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    private sealed class DirectoryRow
    {
        public string Category { get; set; } = string.Empty;
        public string NameEn { get; set; } = string.Empty;
        public string NameBn { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
        public string? AddressEn { get; set; }
        public string? AddressBn { get; set; }
        public string? Phone { get; set; }
        public double? Lat { get; set; }
        public double? Lng { get; set; }
        public bool Is24x7 { get; set; }
        public bool IsVerified { get; set; }
        public string? SourceUrl { get; set; }
    }

    public static async Task RunAsync(WomenSafetyDbContext db, CancellationToken ct = default)
    {
        var jsonPath = ResolveJsonPath();
        if (jsonPath is null)
        {
            Serilog.Log.Warning("Directory seed skipped: Data/directory-entries.json not found");
            return;
        }

        // Fingerprint the dataset so an updated directory-entries.json replaces
        // the previous one instead of silently keeping the stale rows.
        var fingerprint = Convert.ToHexString(
            System.Security.Cryptography.SHA256.HashData(await File.ReadAllBytesAsync(jsonPath, ct)))
            [..12];
        var marker = $"{VersionPrefix}{fingerprint}";

        var existing = await db.DataSources.FirstOrDefaultAsync(d => d.Name == SourceName, ct);
        if (existing is not null && existing.SourceUrl == marker) return;

        await using var stream = File.OpenRead(jsonPath);
        var rows = await JsonSerializer.DeserializeAsync<List<DirectoryRow>>(stream, JsonOptions, ct)
                   ?? new List<DirectoryRow>();

        var districts = await db.Districts.AsNoTracking().ToDictionaryAsync(d => d.NameEn, ct);

        // One-time cleanup of the old six-placeholder-per-district demo entries.
        var legacy = await db.ServiceDirectoryEntries.ToListAsync(ct);
        db.ServiceDirectoryEntries.RemoveRange(legacy);

        var now = DateTimeOffset.UtcNow;
        var added = 0;
        var skipped = 0;

        foreach (var row in rows)
        {
            if (!Enum.TryParse<DirectoryCategory>(row.Category, out var category)
                || !districts.TryGetValue(row.District, out var district))
            {
                skipped++;
                continue;
            }

            db.ServiceDirectoryEntries.Add(new ServiceDirectoryEntry
            {
                Id = Guid.NewGuid(),
                Category = category,
                NameEn = row.NameEn,
                NameBn = row.NameBn,
                DistrictId = district.Id,
                DivisionId = district.DivisionId,
                AddressEn = row.AddressEn,
                AddressBn = row.AddressBn,
                PhoneNumber = string.IsNullOrWhiteSpace(row.Phone) ? null : row.Phone,
                Latitude = row.Lat ?? district.CenterLatitude,
                Longitude = row.Lng ?? district.CenterLongitude,
                Is24x7 = row.Is24x7,
                IsVerified = row.IsVerified,
                SourceUrl = row.SourceUrl,
                CreatedAt = now
            });
            added++;
        }

        if (existing is not null)
        {
            db.DataSources.Remove(existing);
        }
        db.DataSources.Add(new DataSource
        {
            Id = Guid.NewGuid(),
            Name = SourceName,
            // Stores the dataset fingerprint; the directory rows carry the
            // per-entry provenance URLs.
            SourceUrl = marker,
            VerificationStatus = VerificationStatus.PENDING_REVIEW,
            PublishedAt = now,
            IsDemoData = false
        });

        await db.SaveChangesAsync(ct);
        Serilog.Log.Information("Directory seed: {Added} entries added, {Skipped} rows skipped, {Legacy} legacy entries removed",
            added, skipped, legacy.Count);
    }

    private static string? ResolveJsonPath()
    {
        var candidates = new[]
        {
            Path.Combine(AppContext.BaseDirectory, "Data", "directory-entries.json"),
            Path.Combine(Directory.GetCurrentDirectory(), "Data", "directory-entries.json"),
            Path.Combine("Data", "directory-entries.json")
        };
        return candidates.FirstOrDefault(File.Exists);
    }
}